import {
  SiToyota,
  SiNissan,
  SiBmw,
  SiFord,
  SiMazda,
  SiFiat,
  SiAlfaromeo,
  SiLandrover,
  SiAstonmartin,
  SiMaserati,
  SiTesla,
  SiMercedes,
  SiAudi,
  SiSubaru,
  SiMitsubishi,
  SiChrysler,
  SiFerrari,
  SiCitroen,
  SiVolvo,
  SiLamborghini,
  SiBentley,
  SiMini,
  SiHyundai,
} from 'react-icons/si';

const size = '50px';

export const icons = [
  <SiToyota size={size} />,
  <SiNissan size={size} />,
  <SiBmw size={size} />,
  <SiFord size={size} />,
  <SiMazda size={size} />,
  <SiFiat size={size} />,
  <SiAlfaromeo size={size} />,
  <SiLandrover size={size} />,
  <SiAstonmartin size={size} />,
  <SiMaserati size={size} />,
  <SiTesla size={size} />,
  <SiMercedes size={size} />,
  <SiAudi size={size} />,
  <SiSubaru size={size} />,
  <SiMitsubishi size={size} />,
  <SiChrysler size={size} />,
  <SiFerrari size={size} />,
  <SiCitroen size={size} />,
  <SiVolvo size={size} />,
  <SiLamborghini size={size} />,
  <SiBentley size={size} />,
  <SiMini size={size} />,
  <SiHyundai size={size} />,
];

